name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello World" #the command the should be executed in cmd line
    - name: Print bye
      run: echo "bye  bye"
